# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import property_pb2 as property__pb2


class PropertyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Properties = channel.unary_unary(
                '/Property/Properties',
                request_serializer=property__pb2.PropertyRequest.SerializeToString,
                response_deserializer=property__pb2.PropertyReply.FromString,
                )


class PropertyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Properties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PropertyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Properties': grpc.unary_unary_rpc_method_handler(
                    servicer.Properties,
                    request_deserializer=property__pb2.PropertyRequest.FromString,
                    response_serializer=property__pb2.PropertyReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Property', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Property(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Properties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Property/Properties',
            property__pb2.PropertyRequest.SerializeToString,
            property__pb2.PropertyReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
